<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <Company>Wermdö Sport Technologies</Company>
      <Product>CSV Converter</Product>
      <Copyright>
          Copyright © 2026 Wermdö Sport Technologies
      </Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
  </ItemGroup>

</Project>
